### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by vocdex** [facebookresearch/PyTouch#29]
Thank you for the code.
1.I am trying to use the touch_detect.py in pytouch/examples/ folder.  However, it cannot download the model from AWS cloud because of this:
`Ipytouch.models.zoo.PyTouchZooModelNotFound: cannot find model touchdetect_resnet18_DigitSensor.pth`
I had no problem to download the models for surface3d.py example. Is it possible that the model resnet18 was deleted or the name has changed?
2. Is it possible to use surface3d.py in real-time? Currently, in surface3d.py, the 3d reconstructions are created by existing files in dataset. I want to get real-time image input from DIGIT and plot the surface3d in real-time too
3.  In examples/configs/digit_surface3d.yaml file, the gel width and gel_height are given as follows:
`  gel_width: 0.02 # gel width (y-axis) in meters
  gel_height: 0.03 # gel height (x-axis) in meters`
Assuming it is a DIGIT sensor, should  not the gel width be 0.015 and gel_height 0.02? I measured both with a caliper. Did you guys have different DIGIT sensor or am I missing something here?

**Comment by vocdex** [comment]
No updates, so far. Hope the authors can take a lot on these issues

**Comment by AlphaBetaPhi** [comment]
Hi all,

We are working on releasing a new update to address these issues and provide examples that work without modification. These were initially provided as reference examples demonstrating how to use the framework.

**Comment by AlphaBetaPhi** [comment]
Hi @vocdex,

The 3d surface can be reconstructed in real time for sensor output as well as TACTO output. We will provide an example on how to do this. In general, the output from the sensors is provided as a stream of sequential images to the input of the 3d surface task.

**Comment by vocdex** [comment]
Thanks for reply. We were provided with this device from TU Darmdstadt in Germany. I measured the gel height and width from the outside visible part.
