### ISSUE TITLE
Will mesh model of the sensor be provided?

### ISSUE THREAD

**Issue by ShaoxiongYao** [facebookresearch/PyTouch#32]
Hi,

First thank you for providing this repo. For `Visualizer3D` class in `common/visualizer.py`, there is an optional argument `sensor_mesh_file` to have sensor mesh model. I imagine that file refers to the mesh model of plastic part of the sensor. May I ask do you plan to release that mesh file? I will appreciate your help.

**Comment by vocdex** [comment]
Hi,
You can find the mesh model of DIGIT and other sensors here at TACTO's github repo : 
https://github.com/facebookresearch/tacto/tree/main/meshes
Hope this helps.

**Comment by ShaoxiongYao** [comment]
Thank you @vocdex , that was exactly what I was looking for 👍
