### ISSUE TITLE
Runtime error, I don't have gpu, i have to run it in cpu

### ISSUE THREAD

**Issue by Jcastanyo** [facebookresearch/PyTouch#4]
Hello everyone,

First, I want to thank all of you for all the great job you have been doing in this library. Recently, I have been working with DIGIT sensors too and I was able to detect contact or no contact.

I want to compare our results with yours but when I execute touch_detect.py in examples, I receive this error: 
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I don't know how to change this in your code because I usually use Keras and tensforflow. Thanks in advance.

Julio.

**Comment by NileshArnaiya** [comment]
Try configuring CUDA on your gpu or if you don't have a gpu which I highly recommend you need, you can still go ahead and change the function in .local/lib/python3.8/site-packages/torch/serialization.py

`
def validate_cuda_device(location):
    device = torch.cuda._utils._get_device_index(location, True)

    if not torch.cuda.is_available():
        raise RuntimeError('Attempting to deserialize object on a CUDA '
                           'device but torch.cuda.is_available() is False. '
                           'If you are running on a CPU-only machine, '
                           'please use torch.load with map_location=torch.device(\'cpu\') '
                           'to map your storages to the CPU.')
    device_count = torch.cuda.device_count()
    if device >= device_count:
        raise RuntimeError('Attempting to deserialize object on CUDA device '
                           f'{device} but torch.cuda.device_count() is {device_count}. Please use '
                           'torch.load with map_location to map your storages '
                           'to an existing device.')
    return device`
